---
# role: ansible-role-docker
# file: tasks/tasks.yml

- name: "Install packages for docker"
  package:
    name: "{{ docker_packages }}"
    state: present

- name: "Install packages for docker-compose"
  package:
    name: "{{ docker_compose_packages }}"
    state: present
  when: docker_compose | bool

- name: "Ensure /etc/docker exists"
  file:
    path: /etc/docker
    owner: root
    group: root
    mode: 0644
    state: directory
  when: docker_daemon | length > 0

- name: "Remove /etc/docker/daemon.json if empty"
  file:
    path: /etc/docker/daemon.json
    state: absent
  notify: restart and enable docker
  when: docker_daemon | length == 0

- name: "Configure docker daemon"
  template:
    src: etc/docker/daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: restart and enable docker
  when: docker_daemon | length > 0
