---
# role: ansible-role-docker
# file: molecule/vbox/molecule.yml

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: alpine-docker
    box: "generic/alpine312"
    cpus: 2
    memory: 1024
  - name: amazon-docker
    box: "bento/amazonlinux-2"
    cpus: 2
    memory: 1024
  - name: arch-docker
    box: "archlinux/archlinux"
    cpus: 2
    memory: 1024
  - name: centos-docker
    box: "centos/8"
    cpus: 2
    memory: 1024
  - name: debian-docker
    box: "debian/bullseye64"
    cpus: 2
    memory: 1024
  - name: fedora-docker
    box: "fedora/34-cloud-base"
    cpus: 2
    memory: 1024
  - name: opensuse-docker
    box: "generic/opensuse15"
    cpus: 2
    memory: 1024
  - name: oracle-docker
    box: "generic/oracle8"
    cpus: 2
    memory: 1024
  - name: ubuntu-docker
    box: "ubuntu/focal64"
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        docker_role_enabled: true
verifier:
  name: ansible
